### ISSUE TITLE
Cannot find module 'google-assistant'

### ISSUE THREAD

**Issue by Raddy13** [eouia/MMM-Assistant#11]
I'm down to the google-auth.js step, but when I run it, I get this:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'google-assistant'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/google-auth.js:3:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I've got all the Google Assistant libraries installed based on the instructions given in the Google Dev section. Did I miss something else?

**Comment by eouia** [comment]
I think you'd missed something on Step 2.
Try `npm install google-assistant`.

**Comment by E3V3A** [comment]
@Raddy13  Did that solve your problem? If yes, please close issue. 
Mine was resolved by recompiling gprc.
