### ISSUE TITLE
Conversation Error

### ISSUE THREAD

**Issue by JordinGR** [eouia/MMM-Assistant#13]
Everytime the Assistant gets activated the following happens:

```
[ASSTNT] Assistant Activated
Recording with sample rate 16000...
Recording 11026 bytes
End Recording: 657.287ms
Recording 55174 bytes
Recording 11026 bytes
Recording 11026 bytes
Recording 11026 bytes
Recording 11026 bytes
Recording 11026 bytes
[ASSTNT] Conversation Error: { Error: Invalid 'audio_in': audio frame length is too long.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:180:8)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:649:14 code: 3, metadata: Metadata { _internal_repr: {} } }
Recording 11026 bytes
```

**Comment by eouia** [comment]
In most case, that kind of error message was driven from the bad microphone or wrong audio settings.

**Comment by E3V3A** [comment]
@JordinGR  Please confirm your audio and ALSA settings.
