### ISSUE TITLE
gyp ERR! build error

### ISSUE THREAD

**Issue by heoyongun** [eouia/MMM-Assistant#16]
This is my error information.
Somebody help me.

```
pi@raspberrypi:~/MagicMirror $ sudo npm install --save-dev electron-rebuild && ./node_modules/.bin/electron-rebuild --pre-gyp-fix
magicmirror@2.2.2 /home/pi/MagicMirror
└── electron-rebuild@1.7.3 

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.12.3 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/pi/MagicMirror/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/node_modules/uws/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.electron-gyp/.node-gyp/iojs-1.4.15/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.electron-gyp/.node-gyp/iojs-1.4.15',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.electron-gyp/.node-gyp/iojs-1.4.15/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/node_modules/uws',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
make: Entering directory '/home/pi/MagicMirror/node_modules/uws/build'
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
In file included from ../src/WebSocketProtocol.h:5:0,
                 from ../src/WebSocket.h:4,
                 from ../src/Group.h:4,
                 from ../src/Group.cpp:1:
../src/Networking.h:7:30: fatal error: openssl/opensslv.h: No such file or directory
 #include <openssl/opensslv.h>
                              ^
compilation terminated.
uws.target.mk:95: recipe for target 'Release/obj.target/uws/src/Group.o' failed
make: Leaving directory '/home/pi/MagicMirror/node_modules/uws/build'
make: *** [Release/obj.target/uws/src/Group.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/node_modules/.bin/node-gyp" "rebuild" "--target=1.4.15" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/pi/MagicMirror/node_modules/uws
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.12.3 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/pi/MagicMirror/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/node_modules/uws/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.electron-gyp/.node-gyp/iojs-1.4.15/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.electron-gyp/.node-gyp/iojs-1.4.15',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.electron-gyp/.node-gyp/iojs-1.4.15/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/node_modules/uws',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
make: Entering directory '/home/pi/MagicMirror/node_modules/uws/build'
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/uws/src/Extensions.o
  CXX(target) Release/obj.target/uws/src/Group.o
In file included from ../src/WebSocketProtocol.h:5:0,
                 from ../src/WebSocket.h:4,
                 from ../src/Group.h:4,
                 from ../src/Group.cpp:1:
../src/Networking.h:7:30: fatal error: openssl/opensslv.h: No such file or directory
 #include <openssl/opensslv.h>
                              ^
compilation terminated.
uws.target.mk:95: recipe for target 'Release/obj.target/uws/src/Group.o' failed
make: Leaving directory '/home/pi/MagicMirror/node_modules/uws/build'
make: *** [Release/obj.target/uws/src/Group.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/node_modules/.bin/node-gyp" "rebuild" "--target=1.4.15" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /home/pi/MagicMirror/node_modules/uws
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:198:26)
    at Subscriber._error (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:129:26)
    at Subscriber.error (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:103:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:129:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:103:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:248:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/node_modules/rxjs/Subscriber.js:188:27)


```

**Comment by heoyongun** [comment]
I solved it.
Do not proceed through [ssh].
[vnc] is ok.
