### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by afroguys** [eouia/MMM-Assistant#18]
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Module version mismatch. Expected 50, got 48.
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
App threw an error during load
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/bindings/bindings.js:81:44)
Whoops! There was an uncaught exception...
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/bindings/bindings.js:81:44)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

**Comment by eouia** [comment]
I think you've missed or failed something wrong in` Step 4. Post Installation`.

**Comment by afroguys** [comment]
i already do step 4, after finish step 4, i got this error

`Starting MagicMirror: v2.2.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v1.4-linux-arm-glibc
Found: [electron-v1.4-linux-arm-{libc}, node-v48-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/node/extension_binary/electron-v1.4-linux-arm-glibc/grpc_node.node'
`
after run command that suggested from the error msg, `npm rebuild` i got error

`Starting MagicMirror: v2.2.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Module version mismatch. Expected 50, got 48.
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
App threw an error during load
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/bindings/bindings.js:81:44)
Whoops! There was an uncaught exception...
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/bindings/bindings.js:81:44)
`

please help

**Comment by TheCrack3r** [comment]
Hii. Go to the directory where the file [electron-v1.4-linux-arm-{libc} is and rename it to [electron-v1.4-linux-arm-glibc. Let me now

**Comment by afroguys** [comment]
@TheCrack3r,

thank you. it work..... now need to fix the microphone. i buy cheap cam+microphone. 

tested a record command, but not work. maybe need to buy new microphone.

**Comment by TheCrack3r** [comment]
Okey. I would buy a logitech c170. It works perfect for me.

**Comment by afroguys** [comment]
i already buy cheap one from china, i though all microphone is same. but not working for me. maybe need to dig more how to make it work.
