### ISSUE TITLE
Error: spawn arecord ENOENT when starting MagicMirror

### ISSUE THREAD

**Issue by RoySijnesael** [eouia/MMM-Assistant#20]
Just finished installing and when I open my webpage I get this error in my console:

```
[ASSTNT] Snowboy Activated
Whoops! There was an uncaught exception...
{ Error: spawn aplay ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn aplay',
  path: 'aplay',
  spawnargs:
   [ '/Users/roysijnesael/Github/Personal/MagicMirror/modules/MMM-Assistant/resources/beep.mp3' ] }
```

And:

```
Whoops! There was an uncaught exception...
{ Error: spawn arecord ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn arecord',
  path: 'arecord',
  spawnargs: [ '-q', '-r', 16000, '-c', '1', '-t', 'wav', '-f', 'S16_LE', '-' ] }
```

Does anyone known what to do?

**Comment by eouia** [comment]
Your system looks not to have `arecord` or misconfigured for sound system.
Can you record your voice with `arecord` in terminal console mode?

**Comment by E3V3A** [comment]
@RoySijnesael  
Has your problem been resolved? 
If not, please use the **full** config, but use `rec` as the recording program.
