### ISSUE TITLE
Assitant module freezes after some use (Uncaught TypeError)

### ISSUE THREAD

**Issue by E3V3A** [eouia/MMM-Assistant#25]
After having my assistant put to test, it suddenly froze while recording.

`Uncaught TypeError: Cannot read property 'dismiss' of null`
I'm not sure which `alert.js` this come from.

Here is a screenshot:

![2018-03-16-115255_1057x735_scrot](https://user-images.githubusercontent.com/194392/37517866-815ae01a-291b-11e8-80c1-d6bd05372fe9.png)

This might be related to #12.

**Comment by E3V3A** [comment]
This may be related to #9...

**Comment by E3V3A** [comment]
Not sure if related, but I found this in the error log in the updated version when frozen.
```
[ASSTNT] Conversation Error: { Error: Service unavailable.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/client.js:255:19)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/client.js:233:8)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/client.js:757:12 code: 14, metadata: Metadata { _internal_repr: {} } }
```

**Comment by E3V3A** [comment]
Another error that arrived today out-of-the-blue, while using Google.

```
Error: write after end
    at writeAfterEnd (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/readable-stream/lib/_stream_writable.js:288:12)
    at Speaker.Writable.write (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/readable-stream/lib/_stream_writable.js:332:20)
    at Conversation.conversation.on (/home/pi/MagicMirror/modules/MMM-Assistant/node_helper.js:259:21)
    at emitOne (events.js:96:13)
    at Conversation.emit (events.js:188:7)
    at ClientDuplexStream.Conversation.conversation.on (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/conversation.js:118:12)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
```
I have no fcuking idea what this means!   
Anyone else seen this?

If this has anything to do with this module, then line 259 is here:
```js
      conversation
        .on('audio-data', (data) => {
          //record.stop()
          const now = new Date().getTime()
          if (mode == 'ASSISTANT') {
            this.sendSocketNotification('MODE', {mode:'ASSISTANT_SPEAKING'})
            speaker.write(data);             //   <<=== ERROR LINE =================== 
            spokenResponseLength += data.length;
            const audioTime = spokenResponseLength / (this.config.assistant.conversation.audio.sampleRateOut * 16 / 8) * 1000;
            clearTimeout(speakerTimer);
            speakerTimer = setTimeout(() => { speaker.end(); }, audioTime - Math.max(0, now - speakerOpenTime));
          } else {
```

**Comment by E3V3A** [comment]
The original error is coming from Line 133 in [alert.js](https://github.com/MichMich/MagicMirror/blob/develop/modules/default/alert/alert.js#L113):

```js
	hide_alert: function(sender) {
		//Dismiss alert and remove from this.alerts
		this.alerts[sender.name].dismiss();  // <<========= LINE  113 !
		this.alerts[sender.name] = null;
		//Remove overlay
		var overlay = document.getElementById("overlay");
		overlay.parentNode.removeChild(overlay);
},
```

**Comment by E3V3A** [comment]
note:
* all modules are receiving and handling `SHOW_ALERT` and `HIDE_ALERT`...
* `/var/log/auth.log` has some mysterious message:  
  **`Mar 31 18:29:27 xxx systemd-logind[351]: Removed session c30.`**

**Comment by E3V3A** [comment]
This was fixed in MM PR: https://github.com/MichMich/MagicMirror/pull/1248

The other issues now seem unrelated to OP. (Open new issue for those if they re-occur.)

**Comment by E3V3A** [comment]
PS. To fix this while MM `dev` is being considere, fix yourself with:

```js
    hide_alert: function(sender) {
        //Dismiss alert and remove from this.alerts
        if (this.alerts[sender.name]) {
            this.alerts[sender.name].dismiss();
            this.alerts[sender.name] = null;
            //Remove overlay
            var overlay = document.getElementById("overlay");
            overlay.parentNode.removeChild(overlay);
        }
    },
```
