### ISSUE TITLE
TypeError: Speech is not a function

### ISSUE THREAD

**Issue by E3V3A** [eouia/MMM-Assistant#35]
Relevant Branch: `dev`

By chance I failed to give a command after saying `smart-mirror`. Then it froze with the following 
error in the logs:

```
TypeError: Speech is not a function
    at Class.activateCommand (/home/pi/MagicMirror/modules/MMM-Assistant/node_helper.js:355:20)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Assistant/node_helper.js:88:43)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Looking at the code line, we have:
```js
...
  activateCommand: function() {
    this.sendSocketNotification('MODE', {mode:'COMMAND_STARTED'})
    const speech = Speech(this.config.stt.auth[this.commandAuthIndex++])    // ERROR LINE!!
    if (this.commandAuthIndex >= this.commandAuthMax) this.commandAuthIndex = 0
...
```

**Comment by E3V3A** [comment]
@eouia  
I looked in the [Google documents](https://cloud.google.com/nodejs/docs/reference/speech/1.2.x/) for their API, but I find nothing that look like your code.
Do you have any idea about what's going on there? 
(Everything else with GA works, but not MM.)

**Comment by E3V3A** [comment]
There are also a lot of ocmments in this file:
```bash
cd ~/MagicMirror/modules/MMM-Assistant
nano ./node_modules/@google-cloud/speech/src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js
```
