### ISSUE TITLE
MMM-Assistant Node && npm version

### ISSUE THREAD

**Issue by werdnllac** [eouia/MMM-Assistant#43]
Hi, I had raised the concern about this module that could not execute despite following a few steps. 

I have Raspbian Jessie Lite version
Nodejs upgraded to version 9.10.1
npm version 5.8.0
arecord and aplay has no issue playing test.wav and recording.

I noticed only when I uses the nodejs version 6.x.x, MMM-Assistant can be installed. But when I use nodejs version 9x.x, there are plenty of error:

`node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v59-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@9.10.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.9.35-v7+
node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy
node-pre-gyp ERR! node -v v9.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm' (1)
npm WARN The package electron-rebuild is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-03-30T08_47_26_891Z-debug.log`

Please clarify if possible or if MMM-Assistant package is a Beta repository? Thanks

**Comment by E3V3A** [comment]
Hi @werdnllac !

I think your compilation is failing because you're using the `Jessie Lite`. You need the full version to properly compile. I have no idea what dependencies might be missing from Lite. 

> Please clarify if possible or if MMM-Assistant package is a Beta repository?

Everything you find on GitHub is `Beta`!  :1st_place_medal:  

But this package works for other people, so as I say in the README, update your your outdated Raspi OS. 
And as I also ask in the Issue template, make sure to include the commands you used before your error. 

Just out of curiosity, what do these return?
```bash
sudo apt-get update
apt list --upgradable
```
