### ISSUE TITLE
Exceeded maximum allowed stream duration

### ISSUE THREAD

**Issue by drftg** [eouia/MMM-Assistant#52]
After the "command" hot word, if nothing else is spoken a time out is triggered. 
```
Error: 11 OUT_OF_RANGE: Exceeded maximum allowed stream duration of 65 seconds.
``` 
I would expect MMM-Assistant to return to a listening state, waiting for a new hot word to be spoken.
Unfortunately after this error MMM-Assistant becomes unresponsive and does not react to hot words.

**Comment by E3V3A** [comment]
@drftg  Yeah, I got the same error just the other day. Need to look into this. and also we should check if we can use a different way to store the temp file. BTW. **That** error you got, where did you see that?

Mine was:

```
[ASSTNT] Conversation Error: { Error: Invalid 'audio_in': audio frame length is too long.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/client.js:255:19)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/client.js:233:8)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/grpc/src/client.js:757:12 code: 3, metadata: Metadata { _internal_repr: {} } }
[ASSTNT] Conversation Error: Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at ClientDuplexStream.Writable.write (_stream_writable.js:217:5)
    at Conversation.write (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/conversation.js:163:18)
    at Socket.mic.on.data (/home/pi/MagicMirror/modules/MMM-Assistant/node_helper.js:312:43)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

It could also be gPRC problem...

> Unfortunately after this error MMM-Assistant becomes unresponsive and does not react to hot words.

Yep, but if you load the MM from another device, I guess it would reset?

**Comment by drftg** [comment]
This is the log
```
[ASSTNT] RecognizeStream Error:  { Error: 11 OUT_OF_RANGE: Exceeded maximum allowed stream duration of 65 seconds.
    at createStatusError (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:64:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:248:8)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/client.js:804:12
  code: 11,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Object] } },
  details: 'Exceeded maximum allowed stream duration of 65 seconds.' }
```
So storage psace does not seem to be a problem for me

**Comment by E3V3A** [comment]
Yeah, we should set a timeout for this, possibly with a countdown timer shown under the microphone so people know how much they can chat away. After that it should be reset.

**Comment by drftg** [comment]
Showing a countdown is very nice but way more important is resetting. At this moment there are a lot of situations where the assistant "hangs". A watchdog timer would be very helpful.

**Comment by E3V3A** [comment]
@drftg Any ideas how those are implemented?

**Comment by drftg** [comment]
Not yet. The best method is probably within MagicMirror itself but I have not looked at that source yet. Still trying to figure out what makes MMM-Assistant work ;-)

**Comment by drftg** [comment]
Solved:

Someone commented out line 416 in MMM-Assistant.js
```
        //this.sendSocketNotification("HOTWORD_STANDBY")
```
Just put it back and it works again

**Comment by E3V3A** [comment]
Hm, interesting. 
@eouia  You wrote this. Why was it commented out?

**Comment by drftg** [comment]
Whatever the reason, It does not seem to be related to solving any current bug
