### ISSUE TITLE
issue with google-auth.js

### ISSUE THREAD

**Issue by rachnov55** [eouia/MMM-Assistant#53]
```
pi@raspberrypi:~/MagicMirror/modules/MMM-Assistant $ node google-auth.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/google-auth.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
sorry if i shouln't open a new topic on this...but can someone help me here?

**Comment by rachnov55** [comment]
thanks for your reply! managed to locate it and run it but now i get this

```
~/MagicMirror/modules/MMM-Assistant/scripts $ node google-auth.js/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:18
    throw new Error('Missing "keyFilePath" from config (should be where your JSON file is)');
    ^

Error: Missing "keyFilePath" from config (should be where your JSON file is)
    at new Auth (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:18:11)
    at new GoogleAssistant (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/index.js:21:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/scripts/google-auth.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```

**Comment by rachnov55** [comment]
i tried editting the google-auth.js as stated in another thread, and now i get this

```
node google-auth.js
/home/pi/MagicMirror/modules/MMM-Assistant/scripts/google-auth.js:27
const assistant = new GoogleAssistant(config)
^^^^^

SyntaxError: Unexpected token const
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```

sorry for making you deal with a noob like me!

**Comment by rachnov55** [comment]
i changed it to this 
```
const config = {
    keyFilePath: path.resolve(__dirname,     '../assets/google-client-secret.json'), // secret.json
    savedTokensPath: path.resolve(__dirname, '../assets/google-access-tokens.json'), // resources/tokens.js
}
```
I got the secret.json downloaded after enabling api's and setting ownership on google according to the wiki page, and renamed it to google-client-secret.json seeing how that's labelled within the google-auth.js file.  i also placed it in the scripts folder.  I don't have the access token as I can't get google-auth.js working

**Comment by E3V3A** [comment]
I've just updated the script, so please get the latest version.

Then do this:
```bash
# From module home directory
rm assets/google-access-tokens.json
cd scripts
node google-auth.js
```

There will be an error after the url is shown. Just ignore that (it is not related to our script) and paste the key token from the Google request page anyway. Now the file should be created and working.

**Comment by rachnov55** [comment]
that worked now thank you so much!

**Comment by rachnov55** [comment]
during the installtion of the module I got this error
```
> snowboy@1.2.0 install /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v59-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@9.11.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
```
it's not an issue is it?

**Comment by E3V3A** [comment]
No, just let it compile. It can take up to 12 minutes!

**Comment by tadeubanzato** [comment]
I'm having some issues too when I try to run `node google-auth.js` any idea?

Error Message
`node google-auth.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/assets/google-client-secret.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at new Auth (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:26:15)
    at new GoogleAssistant (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/index.js:21:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/scripts/google-auth.js:25:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)`
