### ISSUE TITLE
google authentication process

### ISSUE THREAD

**Issue by Marikolin** [eouia/MMM-Assistant#54]
I followed the steps for authentication and installation. However I was stuck at the part where you have to do "node google-auth.js" it shows 

 node google-auth.js
```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/google-auth.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

Reading another thread, I went into the directory of scripts and ran the same command, which then it showed:

```
/MagicMirror/modules/MMM-Assistant/scripts $ node google-auth.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/assets/google-client-secret.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at new Auth (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:26:15)
    at new GoogleAssistant (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/index.js:21:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/scripts/google-auth.js:25:19)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
```

Please, help.

**Comment by E3V3A** [comment]
wrong location, goto: `cd scripts`

**Comment by Marikolin** [comment]
After going into "/MagicMirror/modules/MMM-Assistant/scripts "
it gives me another error when running "node google-auth.js"

```
 MagicMirror/modules/MMM-Assistant/scripts$ node google-auth.js
 internal/modules/cjs/loader.js:550
 throw err;
 ^
 
 Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/assets/google-client-secret.json'
 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
 at Function.Module._load (internal/modules/cjs/loader.js:475:25)
 at Module.require (internal/modules/cjs/loader.js:598:17)
 at require (internal/modules/cjs/helpers.js:11:18)
 at new Auth (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:26:15)
 at new GoogleAssistant (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/index.js:21:16)
 at Object. (/home/pi/MagicMirror/modules/MMM-Assistant/scripts/google-auth.js:25:19)
 at Module._compile (internal/modules/cjs/loader.js:654:30)
 at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
 at Module.load (internal/modules/cjs/loader.js:566:32)
```

**Comment by E3V3A** [comment]
@Marikolin Sorry, but I don't think you've followed the installation instructions. Please try again from the beginning and make sure you execute all the steps in the right order.
