### ISSUE TITLE
Setting up jarvis.umdl

### ISSUE THREAD

**Issue by Jacob-Meischner** [eouia/MMM-Assistant#74]
I just got this fully working finally and the last step I would like to do is change my assistant .umdl to jarvis instead of snowboy.  I see that you need to put 2 sensitivities in for jarvis and also change the ApplyFrontend to true.  I am completely lost on how to do this, I don't know a whole lot about coding so bare with me please!  Would these changes just be a matter of editing the module in the config.js or do I need to go somewhere else to make the changes?

Thanks in advance!

**Comment by eouia** [comment]
Sorry for my absence, I was stuck in my real world. sorry again.
Frankly says, I'm not supporting this module anymore. I was so disappointed with this module's complexity and difficulty to maintain. A half was due to my poor skill, and the other half was due to incomplete Google Assistant SDK and MagicMirror-Electron problems and... even snowboy stuffs.

Anyway, Maybe this could be help.
```javascript
file: 'resources/models/jarvis.umdl',
sensitivity: '0.8,0.80',
hotwords: ['jarvis','jarvis'] 
```

**Comment by Jacob-Meischner** [comment]
No problem man, real world unfortunately comes first haha.  I replaced what you said in my module and FINALLY it recognized the jarvis hotword when I said it but the microphone immediately turned red and did not respond to my command.  I did a ```pm2 logs``` and this is what it gave me.

```PM2        | [2018-07-04 13:06:08] PM2 log: App [MagicMirror] with id [0] and pid [2075], exited with code [0] via signal [SIGINT]
PM2        | [2018-07-04 13:06:08] PM2 log: pid=2075 msg=process killed
PM2        | [2018-07-04 13:06:50] PM2 log: Starting execution sequence in -fork mode- for app name:MagicMirror id:0
PM2        | [2018-07-04 13:06:50] PM2 log: App name:MagicMirror id:0 online
PM2        | [2018-07-04 13:08:40] PM2 log: Stopping app:MagicMirror id:0
PM2        | [2018-07-04 13:08:40] PM2 log: App [MagicMirror] with id [0] and pid [2325], exited with code [0] via signal [SIGINT]
PM2        | [2018-07-04 13:08:40] PM2 log: pid=2325 msg=process killed
PM2        | [2018-07-04 13:13:47] PM2 log: Starting execution sequence in -fork mode- for app name:MagicMirror id:0
PM2        | [2018-07-04 13:13:47] PM2 log: App name:MagicMirror id:0 online
PM2        | [2018-07-04 13:14:59] PM2 log: App [MagicMirror] with id [0] and pid [2959], exited with code [0] via signal [SIGINT]
PM2        | [2018-07-04 13:14:59] PM2 log: Starting execution sequence in -fork mode- for app name:MagicMirror id:0
PM2        | [2018-07-04 13:14:59] PM2 log: App name:MagicMirror id:0 online
PM2        | [2018-07-04 13:15:05] PM2 log: Stopping app:MagicMirror id:0
PM2        | [2018-07-04 13:15:06] PM2 log: App [MagicMirror] with id [0] and pid [3142], exited with code [0] via signal [SIGINT]
PM2        | [2018-07-04 13:15:06] PM2 log: pid=3142 msg=process killed

/home/pi/.pm2/logs/MagicMirror-error-0.log last 15 lines:
0|MagicMir | 
0|MagicMir | (process:2360): Gtk-WARNING **: Locale not supported by C library.
0|MagicMir | 	Using the fallback 'C' locale.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | 
0|MagicMir | (process:2994): Gtk-WARNING **: Locale not supported by C library.
0|MagicMir | 	Using the fallback 'C' locale.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | 
0|MagicMir | (process:3177): Gtk-WARNING **: Locale not supported by C library.
0|MagicMir | 	Using the fallback 'C' locale.
```

**Comment by Jacob-Meischner** [comment]
Just for giggles I tried using

 **resources/models/jarvis.umdl**: Universal model for the hotword "Jarvis" (https://snowboy.kitt.ai/hotword/29). It has two different models for the hotword Jarvis, so you have to use two sensitivites and two hotwords. Set sensitivities to "0.8,0.80", hotwords to "['jarvis1','jarvis2']" and ApplyFrontend to true. 

from one of the snowboy PR's https://github.com/Kitt-AI/snowboy/pull/448/commits/9c1c9a99f00228c1bd5e1ae647f0c09b140d5352 but that didn't work either.

**Comment by eouia** [comment]
I doubt it is not related with snowboy. `Gtk` is Graphic Tool Kit, so it means GTK problem could be related with graphical issue - especially `electron` updated to 2.0.
That might be out of my ability, sorry.

**Comment by meischdaddy30** [comment]
Okay, it's weird too that when I put my snowboy path and settings back in, it still gives me the same gtk and MESA-LOADER errors but it recognizes and responds to my hotword and commands.  Maybe jarvis just isn't in the cards for me :(  thanks for your help though!

**Comment by meischdaddy30** [comment]
@eouia I just realized I wasn't logging the correct folder..any say on this error?

`0|MagicMir |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|MagicMir |     at emitTwo (events.js:126:13)
0|MagicMir |     at Socket.emit (events.js:214:7)
0|MagicMir |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|MagicMir |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by meischdaddy30** [comment]
meh, now it's not giving me that, it's just saying `[ASSTNT] Snowboy Activated` and nothing afterwords..so not sure what is going on.

**Comment by meischdaddy30** [comment]
@eouia sorry this is the last time I'll comment but I would like someones opinion who knows what they're doing because I've never done this before.

This is my Java.demo file:


import ai.kitt.snowboy.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;

public class Demo {
  static {
    System.loadLibrary("snowboy-detect-java");
  }

  public static void main(String[] args) {
    // Sets up audio.
    AudioFormat format = new AudioFormat(16000, 16, 1, true, false);
    DataLine.Info targetInfo = new DataLine.Info(TargetDataLine.class, format);

    // Sets up Snowboy.
    SnowboyDetect detector = new SnowboyDetect("resources/common.res",
                                               "resources/models/snowboy.umdl");
    detector.SetSensitivity("0.5");
    detector.SetAudioGain(1);
    **detector.ApplyFrontend(true);**
    **detector.SetAudioGain(1);**

    try {
      TargetDataLine targetLine =
        (TargetDataLine) AudioSystem.getLine(targetInfo);
      targetLine.open(format);
      targetLine.start();
      
      // Reads 0.1 second of audio in each call.
      byte[] targetData = new byte[3200];
      short[] snowboyData = new short[1600];
      int numBytesRead;

      while (true) {
        // Reads the audio data in the blocking mode. If you are on a very slow
        // machine such that the hotword detector could not process the audio
        // data in real time, this will cause problem...
        numBytesRead = targetLine.read(targetData, 0, targetData.length);

        if (numBytesRead == -1) {
          System.out.print("Fails to read audio data.");
          break;
        }

        // Converts bytes into int16 that Snowboy will read.
        ByteBuffer.wrap(targetData).order(
            ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(snowboyData);

        // Detection.
        int result = detector.RunDetection(snowboyData, snowboyData.length);
        if (result > 0) {
          System.out.print("Hotword " + result + " detected!\n");
        }
      }
    } catch (Exception e) {
      System.err.println(e);
    }
  }
}

After I make those changes I'm supposed to compile the Demo.java by using

javac Demo.java

then after I do that it should create a Demo.class file.  So I run the .class file by using

java Demo

and it should work.  So my question is, after I re-compile the Demo.java and make sure it works, I should be able to run my MagicMirror and should be able to use jarvis right?

And what should I do with my old .class file?
