### ISSUE TITLE
MMM-Assistant crashes on start

### ISSUE THREAD

**Issue by StefanMeGit** [eouia/MMM-Assistant#8]
```
0|MagicMir | WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/node/extension_binary/electron-v1.7-linux-arm-glibc/grpc_node.node'
0|MagicMir | App threw an error during load
0|MagicMir | Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/node/extension_binary/electron-v1.7-linux-arm-glibc/grpc_node.node'
0|MagicMir |     at Module._resolveFilename (module.js:470:15)
0|MagicMir |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|MagicMir |     at Function.Module._load (module.js:418:25)
0|MagicMir |     at Module.require (module.js:498:17)
0|MagicMir |     at require (internal/module.js:20:19)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/grpc_extension.js:30:15)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/grpc_extension.js:34:3)
0|MagicMir |     at Module._compile (module.js:571:32)
0|MagicMir |     at Object.Module._extensions..js (module.js:580:10)
0|MagicMir |     at Module.load (module.js:488:32)
0|MagicMir | { Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/node/extension_binary/electron-v1.7-linux-arm-glibc/grpc_node.node'
0|MagicMir |     at Module._resolveFilename (module.js:470:15)
0|MagicMir |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|MagicMir |     at Function.Module._load (module.js:418:25)
0|MagicMir |     at Module.require (module.js:498:17)
0|MagicMir |     at require (internal/module.js:20:19)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/grpc_extension.js:30:15)
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/grpc_extension.js:34:3)
0|MagicMir |     at Module._compile (module.js:571:32)
0|MagicMir |     at Object.Module._extensions..js (module.js:580:10)
0|MagicMir |     at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
```

did already your **Cannot find module... (esp. related with electron ver 1.7)**... what else can i do?

**Comment by eouia** [comment]
go to your `/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/grpc/src/node/extension_binary/`, then you can see `electron-v1.7-linux-arm-{lib}` or something similar else.
change its name with `electron-v1.7-linux-arm-glbc`.

**Comment by StefanMeGit** [comment]
Ok that worked great! 

Now i got it running but got a strange message when i activate snowboy.

0|MagicMir | [ASSTNT] Snowboy Activated
0|MagicMir | [ASSTNT] Assistant Activated
0|MagicMir | [ASSTNT] GA Transcription:  how are you

and it answers "Give me permission to help you"... means something with my keyFile is not ok?

**Comment by eouia** [comment]
Hmmm.. I think you havn't given a permission of your account for using Google Assistant.
Did you activate `google-auth.js` on your MM? It would try to open a browser and wait for your permission of using Google Assistant on your MM.

**Comment by StefanMeGit** [comment]
Yes i did. Worked fine.

I ll try it again. Give u response in a few.

**Comment by StefanMeGit** [comment]
No, did the whole routine again... 

```
secret.json (OAuth 2.0 client IDs / Type: other):
Set the Configure consent screen. You need to set only Product name shown to users.
Select Application Type as other and give the name. Now you can get oAuth.
Download your client-secret-blahblahXXX.json and rename it as secret.json. Put that file in MMM-Assistant directory.
```

```
token.js created:
It will try to open the browser for getting some credential keystring. copy and paste it where the google-auth.js prompts.
Now, you can find token.js under resources directory. Keep it safely.
```

```
MagicMirrorAssistant-2c76c856fba5.json created:
Select Create Credentials and Service Account Key. (It's obvious to be able to use secret.json again. For safe, I'll create another key file for Google Cloud Speech)

Set the details (anything for service account name, Project>Owner for Role, anything for service account id, JSON for key type. After set, you can download your key file.

It will be used in config.stt.auth
-> MagicMirrorAssistant-2c76c856fba5.json

```

```
		  module: 'MMM-Assistant',
		  position: 'upper_third',
		  config: {
		    assistant: {
		      auth: {
		        keyFilePath: "secret.json", //When you want to change the location of this file, set this.
		        savedTokensPath: "resources/tokens.js" //When you want to change the location of this file, set this.
		      },
		      audio: {
		        encodingIn: "LINEAR16", //Ignore this. I think you don't need to change this.
		        sampleRateOut: 16000 //Ignore this. I think you don't need to change this.
		      }
		    },
		    snowboy: {
		      models: [
		        {
		          file: "resources/smart_mirror.umdl",
		          sensitivity: 0.5,
		          hotwords : "MIRROR" //One of models should be "MIRROR"
		        },
		        {
		          file: "resources/snowboy.umdl",
		          sensitivity: 0.5,
		          hotwords : "ASSISTANT" //One of models should be "ASSISTANT"
		        }
		      ]
		    },
		    record: {
		      threshold: 0, //Ignore this. I think you don't need to change this.
		      verbose:false, //true for checking recording status.
		      recordProgram: 'arecord', //You can use 'rec', 'sox'. But I recommend use 'arecord'.
		      silence: 2.0 //Ignore this. I think you don't need to change this.
		    },
		    stt: {
		      auth: [{
		        projectId: 'magicmirrorassistant-188817', //ProjectId from Google Console
		        keyFilename: 'MagicMirrorAssistant-2c76c856fba5.json'
		      }], //You can use multi accounts for saving money.
		      request: {
		        encoding: 'LINEAR16', //Ignore this. I think you don't need to change this.
		        sampleRateHertz: 16000, //Ignore this. I think you don't need to change this.
		        languageCode: 'en-US' //See https://cloud.google.com/speech/docs/languages
		      },
		    },
		    speak: {
		      useAlert: true, //If you want to show the text of speech, set this true. But It could be ignored by command of modules directly.
		      language: 'en-US', //If you want to set the default language of speech of command result, set this.
		    },
		    alias: [
		      {
		        "help :command" : ["teach me :command", "what is :command"]
		      }
		    ] // You can use aliases for difficult pronunciation or easy using.
		  }
		},
```

But he still just say "give me permission to help u"

its frustrating...

**Comment by StefanMeGit** [comment]
Solved it.

U need to give permission for speech & audo activitys...

https://myaccount.google.com/activitycontrols?utm_source=my-activity&utm_medium=home&utm_campaign&continue=https://myactivity.google.com/myactivity?utm_campaign%3Dcontinue&pli=1

**Comment by eouia** [comment]
Good for you. I'll close this issue.

**Comment by E3V3A** [comment]
@StefanMeGit  Can you tell us in more detail what you did?
